# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:/QT/QT/所有项目/项目_20191027_功能程序/ui2a3.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class ui2a3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1085, 577)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rc_inpu = QtWidgets.QTextEdit(self.centralwidget)
        self.rc_inpu.setGeometry(QtCore.QRect(20, 60, 301, 81))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.rc_inpu.setFont(font)
        self.rc_inpu.setObjectName("rc_inpu")
        self.rc_oupt = QtWidgets.QTextEdit(self.centralwidget)
        self.rc_oupt.setGeometry(QtCore.QRect(20, 180, 301, 351))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.rc_oupt.setFont(font)
        self.rc_oupt.setObjectName("rc_oupt")
        self.rc_state = QtWidgets.QLabel(self.centralwidget)
        self.rc_state.setGeometry(QtCore.QRect(20, 150, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.rc_state.setFont(font)
        self.rc_state.setInputMethodHints(QtCore.Qt.ImhNone)
        self.rc_state.setAlignment(QtCore.Qt.AlignCenter)
        self.rc_state.setObjectName("rc_state")
        self.pc_fileInpt = QtWidgets.QTextEdit(self.centralwidget)
        self.pc_fileInpt.setGeometry(QtCore.QRect(360, 80, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pc_fileInpt.setFont(font)
        self.pc_fileInpt.setObjectName("pc_fileInpt")
        self.pc_title = QtWidgets.QLabel(self.centralwidget)
        self.pc_title.setGeometry(QtCore.QRect(360, 30, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(15)
        self.pc_title.setFont(font)
        self.pc_title.setAlignment(QtCore.Qt.AlignCenter)
        self.pc_title.setObjectName("pc_title")
        self.pc_pathInpt1 = QtWidgets.QTextEdit(self.centralwidget)
        self.pc_pathInpt1.setGeometry(QtCore.QRect(360, 160, 301, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pc_pathInpt1.setFont(font)
        self.pc_pathInpt1.setObjectName("pc_pathInpt1")
        self.pc_fileTitle = QtWidgets.QLabel(self.centralwidget)
        self.pc_fileTitle.setGeometry(QtCore.QRect(360, 60, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pc_fileTitle.setFont(font)
        self.pc_fileTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.pc_fileTitle.setObjectName("pc_fileTitle")
        self.pc_pathTitle1 = QtWidgets.QLabel(self.centralwidget)
        self.pc_pathTitle1.setGeometry(QtCore.QRect(360, 140, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pc_pathTitle1.setFont(font)
        self.pc_pathTitle1.setAlignment(QtCore.Qt.AlignCenter)
        self.pc_pathTitle1.setObjectName("pc_pathTitle1")
        self.rc_title = QtWidgets.QLabel(self.centralwidget)
        self.rc_title.setGeometry(QtCore.QRect(20, 30, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(15)
        self.rc_title.setFont(font)
        self.rc_title.setAlignment(QtCore.Qt.AlignCenter)
        self.rc_title.setObjectName("rc_title")
        self.pc_pathTitle2 = QtWidgets.QLabel(self.centralwidget)
        self.pc_pathTitle2.setGeometry(QtCore.QRect(360, 220, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pc_pathTitle2.setFont(font)
        self.pc_pathTitle2.setAlignment(QtCore.Qt.AlignCenter)
        self.pc_pathTitle2.setObjectName("pc_pathTitle2")
        self.pc_pathInpt2 = QtWidgets.QTextEdit(self.centralwidget)
        self.pc_pathInpt2.setGeometry(QtCore.QRect(360, 240, 301, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pc_pathInpt2.setFont(font)
        self.pc_pathInpt2.setObjectName("pc_pathInpt2")
        self.pc_pathTitle3 = QtWidgets.QLabel(self.centralwidget)
        self.pc_pathTitle3.setGeometry(QtCore.QRect(360, 300, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pc_pathTitle3.setFont(font)
        self.pc_pathTitle3.setAlignment(QtCore.Qt.AlignCenter)
        self.pc_pathTitle3.setObjectName("pc_pathTitle3")
        self.pc_pathInpt3 = QtWidgets.QTextEdit(self.centralwidget)
        self.pc_pathInpt3.setGeometry(QtCore.QRect(360, 320, 301, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pc_pathInpt3.setFont(font)
        self.pc_pathInpt3.setObjectName("pc_pathInpt3")
        self.pc_submit = QtWidgets.QPushButton(self.centralwidget)
        self.pc_submit.setGeometry(QtCore.QRect(480, 380, 65, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pc_submit.setFont(font)
        self.pc_submit.setObjectName("pc_submit")
        self.pc_state = QtWidgets.QLabel(self.centralwidget)
        self.pc_state.setGeometry(QtCore.QRect(360, 450, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pc_state.setFont(font)
        self.pc_state.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pc_state.setAlignment(QtCore.Qt.AlignCenter)
        self.pc_state.setObjectName("pc_state")
        self.bk_textOupt = QtWidgets.QTextBrowser(self.centralwidget)
        self.bk_textOupt.setGeometry(QtCore.QRect(690, 100, 351, 311))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(11)
        self.bk_textOupt.setFont(font)
        self.bk_textOupt.setObjectName("bk_textOupt")
        self.bk_addBtn = QtWidgets.QPushButton(self.centralwidget)
        self.bk_addBtn.setGeometry(QtCore.QRect(970, 420, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.bk_addBtn.setFont(font)
        self.bk_addBtn.setObjectName("bk_addBtn")
        self.bk_popBtn = QtWidgets.QPushButton(self.centralwidget)
        self.bk_popBtn.setGeometry(QtCore.QRect(970, 520, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(12)
        font.setItalic(False)
        font.setUnderline(False)
        self.bk_popBtn.setFont(font)
        self.bk_popBtn.setObjectName("bk_popBtn")
        self.bk_upackBtn = QtWidgets.QPushButton(self.centralwidget)
        self.bk_upackBtn.setGeometry(QtCore.QRect(960, 70, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(12)
        font.setItalic(False)
        font.setUnderline(False)
        self.bk_upackBtn.setFont(font)
        self.bk_upackBtn.setObjectName("bk_upackBtn")
        self.bk_saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.bk_saveBtn.setGeometry(QtCore.QRect(690, 70, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(12)
        font.setItalic(False)
        font.setUnderline(False)
        self.bk_saveBtn.setFont(font)
        self.bk_saveBtn.setObjectName("bk_saveBtn")
        self.bk_addPopEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.bk_addPopEdit.setGeometry(QtCore.QRect(690, 420, 271, 121))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.bk_addPopEdit.setFont(font)
        self.bk_addPopEdit.setObjectName("bk_addPopEdit")
        self.bk_time = QtWidgets.QLabel(self.centralwidget)
        self.bk_time.setGeometry(QtCore.QRect(850, 70, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bk_time.setFont(font)
        self.bk_time.setObjectName("bk_time")
        self.bk_title = QtWidgets.QLabel(self.centralwidget)
        self.bk_title.setGeometry(QtCore.QRect(690, 30, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(15)
        self.bk_title.setFont(font)
        self.bk_title.setAlignment(QtCore.Qt.AlignCenter)
        self.bk_title.setObjectName("bk_title")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.win_act1 = QtWidgets.QAction(MainWindow)
        self.win_act1.setObjectName("win_act1")
        self.win_act2 = QtWidgets.QAction(MainWindow)
        self.win_act2.setObjectName("win_act2")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "功能程序"))
        self.rc_oupt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'楷体\';\"><br /></p></body></html>"))
        self.rc_state.setText(_translate("MainWindow", "State"))
        self.pc_title.setText(_translate("MainWindow", "程序建造"))
        self.pc_pathInpt1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'楷体\';\"><br /></p></body></html>"))
        self.pc_fileTitle.setText(_translate("MainWindow", "主脚本文件"))
        self.pc_pathTitle1.setText(_translate("MainWindow", "依赖路径 1"))
        self.rc_title.setText(_translate("MainWindow", "识别与转换"))
        self.pc_pathTitle2.setText(_translate("MainWindow", "依赖路径 2"))
        self.pc_pathInpt2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'楷体\';\"><br /></p></body></html>"))
        self.pc_pathTitle3.setText(_translate("MainWindow", "依赖路径 3"))
        self.pc_pathInpt3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'楷体\';\"><br /></p></body></html>"))
        self.pc_submit.setText(_translate("MainWindow", "建造"))
        self.pc_state.setText(_translate("MainWindow", "State"))
        self.bk_textOupt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Adobe 宋体 Std L\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>"))
        self.bk_addBtn.setText(_translate("MainWindow", "添加"))
        self.bk_popBtn.setText(_translate("MainWindow", "删除"))
        self.bk_upackBtn.setText(_translate("MainWindow", "解压"))
        self.bk_saveBtn.setText(_translate("MainWindow", "备份"))
        self.bk_time.setText(_translate("MainWindow", "解压用时:"))
        self.bk_title.setText(_translate("MainWindow", "程序备份"))
        self.win_act1.setText(_translate("MainWindow", "窗口1"))
        self.win_act2.setText(_translate("MainWindow", "窗口2"))

